In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv("Sales_January_2019.csv")

# 1. Ventas totales por año de construcción
sales_by_year = df.groupby("Product")["Price Each"].sum().reset_index()

,Product,Price Each
0,20in Monitor,109.99109.99109.99109.99109.99109.99109.99109....
1,27in 4K Gaming Monitor,389.99389.99389.99389.99389.99389.99389.99389....
2,27in FHD Monitor,149.99149.99149.99149.99149.99149.99149.99149....
3,34in Ultrawide Monitor,379.99379.99379.99379.99379.99379.99379.99379....
4,AA Batteries (4-pack),3.843.843.843.843.843.843.843.843.843.843.843....
5,AAA Batteries (4-pack),2.992.992.992.992.992.992.992.992.992.992.992....
6,Apple Airpods Headphones,1501501501501501501501501501501501501501501501...
7,Bose SoundSport Headphones,99.9999.9999.9999.9999.9999.9999.9999.9999.999...
8,Flatscreen TV,3003003003003003003003003003003003003003003003...
9,Google Phone,6006006006006006006006006006006006006006006006...
10,LG Dryer,600.0600.0600.0600.0600.0600.0600.0600.0600.06...
11,LG Washing Machine,600.0600.0600.0600.0600.0600.0600.0600.0600.06...
12,Lightning Charging Cable,14.9514.9514.9514.9514.9514.9514.9514.9514.951...
13,Macbook Pro Laptop,1700170017001700170017001700170017001700170017...
14,Product,Price EachPrice EachPrice EachPrice EachPrice ...
15,ThinkPad Laptop,999.99999.99999.99999.99999.99999.99999.99999....
16,USB-C Charging Cable,11.9511.9511.9511.9511.9511.9511.9511.9511.951...
17,Vareebadd Phone,4004004004004004004004004004004004004004004004...
18,Wired Headphones,11.9911.9911.9911.9911.9911.9911.9911.9911.991...
19,iPhone,7007007007007007007007007007007007007007007007...

In [6]:
# Cambio de tipo de valor
df["Price Each"] = pd.to_numeric(df["Price Each"], errors = "coerce")

# 1. Ventas totales por año de construcción
sales_by_year = df.groupby("Product")["Price Each"].sum().reset_index().sort_values(by = "Price Each", ascending = False)
sales_by_year

                       Product  Price Each
13          Macbook Pro Laptop   399500.00
19                      iPhone   265300.00
15             ThinkPad Laptop   215997.84
9                 Google Phone   190200.00
1       27in 4K Gaming Monitor   121676.88
6     Apple Airpods Headphones   121350.00
3       34in Ultrawide Monitor   118936.87
8                Flatscreen TV    72900.00
7   Bose SoundSport Headphones    65593.44
2             27in FHD Monitor    62695.82
17             Vareebadd Phone    49600.00
11          LG Washing Machine    25200.00
0                 20in Monitor    23427.87
10                    LG Dryer    23400.00
12    Lightning Charging Cable    15966.60
16        USB-C Charging Cable    13993.45
18            Wired Headphones    12049.95
4        AA Batteries (4-pack)     3989.76
5       AAA Batteries (4-pack)     3235.18
14                     Product        0.00